import streamlit as st
import numpy as np
import plotly.graph_objects as go
from sympy import symbols, integrate, pi, lambdify, sympify
import openai

# 1. Page Configuration
st.set_page_config(page_title="AI Calculus Solver", layout="wide")

# ضعي مفتاح الـ API الخاص بك هنا ليعمل تحليل النصوص
# openai.api_key = "YOUR_OPENAI_API_KEY"

st.title("📐 AI-Powered 3D Volume Solver")
st.write("Type your full English question below. The AI will extract the math and build the 3D solid.")

# 2. Input Area for the Full Question
full_question = st.text_area("Enter the full word problem:", 
                            placeholder="e.g., Find the volume of the solid generated by revolving the region bounded by y=x^2 and y=0 from x=0 to x=2 about the x-axis.")

if st.button("Analyze & Solve"):
    if full_question:
        try:
            # محاكاة لعمل الذكاء الاصطناعي (بإمكانك ربطه فعلياً بـ OpenAI هنا)
            # سنقوم هنا ببرمجة "مستخرج" بسيط أو يدوي للمثال
            # في البرمجة الحقيقية، الـ AI يرسل هذه القيم للموقع:
            
            # مثال لبيانات مستخرجة (هذه القيم سيحددها الـ AI بناءً على سؤالك)
            st.info("AI is analyzing the text and extracting parameters...")
            
            # سنفترض أن المستخدم أدخل سؤالاً عن y=sqrt(x) كمثال للاختبار
            f_text = "sqrt(x)" # سيستخرجها الـ AI
            g_text = "0"       # سيستخرجها الـ AI
            a_val, b_val = 0, 4 # سيستخرجها الـ AI
            axis = "x-axis"

            v_sym = symbols('x')
            f_expr = sympify(f_text)
            g_expr = sympify(g_text)

            # --- Logic & Math ---
            method = "Disk Method" if g_expr == 0 else "Washer Method"
            integrand = f_expr**2 - g_expr**2
            
            col1, col2 = st.columns([1, 1])

            with col1:
                st.subheader("Step-by-Step Solution")
                st.write(f"**Method Identified:** {method}")
                
                st.write("**1. Setup the Integral:**")
                st.latex(f"V = \pi \int_{{{a_val}}}^{{{b_val}}} ({integrand}) dx")

                antiderivative = integrate(integrand, v_sym)
                result_exact = integrate(integrand, (v_sym, a_val, b_val)) * pi
                
                st.write("**2. Integration:**")
                st.latex(f"\pi \left[ {antiderivative} \\right]_{{{a_val}}}^{{{b_val}}}")
                st.success(f"**Final Volume:** {result_exact.evalf():.4f} units³")

            with col2:
                st.subheader("3. 3D Model")
                
                u = np.linspace(float(a_val), float(b_val), 60)
                v = np.linspace(0, 2 * np.pi, 60)
                U, V = np.meshgrid(u, v)
                f_num = lambdify(v_sym, f_expr, 'numpy')
                g_num = lambdify(v_sym, g_expr, 'numpy')

                # Rotation Logic
                X = U
                Y = f_num(U) * np.cos(V)
                Z = f_num(U) * np.sin(V)
                
                fig = go.Figure()
                fig.add_trace(go.Surface(x=X, y=Y, z=Z, colorscale='Reds', opacity=0.8, showscale=False))
                
                if g_expr != 0:
                    Y_in = g_num(U) * np.cos(V)
                    Z_in = g_num(U) * np.sin(V)
                    fig.add_trace(go.Surface(x=X, y=Y_in, z=Z_in, colorscale='Blues', opacity=0.9, showscale=False))

                fig.update_layout(scene=dict(xaxis_title='X', yaxis_title='Y', zaxis_title='Z'))
                st.plotly_chart(fig, use_container_width=True)

        except Exception as e:
            st.error(f"Could not parse the question. Please ensure it's clear. Error: {e}")
    else:
        st.warning("Please enter a question first.")
