import streamlit as st
import numpy as np
import plotly.graph_objects as go
from sympy import symbols, integrate, pi, lambdify, sympify
import re

# إعدادات الصفحة
st.set_page_config(page_title="Math Word Problem Solver", layout="wide")

st.title("📐 Smart 3D Calculus Solver")
st.write("Paste your full English question below, and I will extract the math and build the 3D solid.")

# 1. منطقة إدخال السؤال كاملاً
full_question = st.text_area("Enter your full question here:", 
                            height=150,
                            placeholder="e.g., Find the volume of the solid generated by revolving the region bounded by y=x**2 and y=0 from x=0 to x=2 about the x-axis.")

# دالة بسيطة لاستخراج البيانات من النص (بدون AI خارجي لتجنب الـ Error)
def extract_data(text):
    # البحث عن الدوال باستخدام Regular Expressions
    functions = re.findall(r'[yf]\(?[xy]\)?\s*=\s*([^,\s]+)', text)
    limits = re.findall(r'([0-9.]+)', text)
    
    # قيم افتراضية في حال فشل الاستخراج التلقائي
    f = functions[0] if len(functions) > 0 else "x**2"
    g = functions[1] if len(functions) > 1 else "0"
    a = float(limits[-2]) if len(limits) >= 2 else 0.0
    b = float(limits[-1]) if len(limits) >= 1 else 2.0
    
    return f, g, a, b

if st.button("Analyze & Solve"):
    try:
        # استخراج المعطيات من النص
        f_text, g_text, a_val, b_val = extract_data(full_question)
        
        x = symbols('x')
        f_expr = sympify(f_text)
        g_expr = sympify(g_text)

        method = "Disk Method" if g_expr == 0 else "Washer Method"
        integrand = f_expr**2 - g_expr**2
        
        col1, col2 = st.columns([1, 1])

        with col1:
            st.subheader("Step-by-Step Solution")
            st.info(f"AI detected: f(x)={f_text}, g(x)={g_text}, from {a_val} to {b_val}")
            
            st.write("**1. Setup:**")
            st.latex(f"V = \pi \int_{{{a_val}}}^{{{b_val}}} ({integrand}) dx")

            # الحسابات
            antiderivative = integrate(integrand, x)
            result_exact = integrate(integrand, (x, a_val, b_val)) * pi
            
            st.write("**2. Integration:**")
            st.latex(f"\pi \left[ {antiderivative} \\right]_{{{a_val}}}^{{{b_val}}}")
            st.success(f"Final Volume ≈ {float(result_exact.evalf()):.4f}")

        with col2:
            st.subheader("3D Interactive Model")
            # رسم المجسم ثلاثي الأبعاد
            u = np.linspace(float(a_val), float(b_val), 50)
            v = np.linspace(0, 2 * np.pi, 50)
            U, V = np.meshgrid(u, v)
            f_num = lambdify(x, f_expr, 'numpy')
            g_num = lambdify(x, g_expr, 'numpy')

            X, Y, Z = U, f_num(U) * np.cos(V), f_num(U) * np.sin(V)
            
            fig = go.Figure()
            fig.add_trace(go.Surface(x=X, y=Y, z=Z, colorscale='Reds', opacity=0.8, showscale=False))
            
            if g_expr != 0:
                Y_in, Z_in = g_num(U) * np.cos(V), g_num(U) * np.sin(V)
                fig.add_trace(go.Surface(x=X, y=Y_in, z=Z_in, colorscale='Blues', opacity=0.9, showscale=False))

            st.plotly_chart(fig, use_container_width=True)

    except Exception as e:
        st.error(f"Error: {e}. Please make sure functions are written clearly (e.g., x**2).")
