import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from sympy import symbols, integrate, pi, lambdify, sympify
import openai
import json

# 1. إعداد واجهة الموقع وتصميمها (UI/UX)
st.set_page_config(page_title="Math Solver: Disks & Washers", layout="centered")

st.title("📐 Calculus Volume AI Solver")
st.markdown("""
هذا الموقع مصمم ليحل مسائل **الحجوم الدورانية** من درس 6.2. 
أدخل السؤال بالإنجليزية، وسيقوم الموقع بتحديد الطريقة ورسم الخطوات.
""")

# 2. إعدادات OpenAI للتعامل مع الأسئلة الكلامية
# ملاحظة: يجب وضع المفتاح الخاص بك هنا ليعمل الجزء الخاص بالذكاء الاصطناعي
openai.api_key = "YOUR_OPENAI_API_KEY"

def parse_problem_with_ai(question_text):
    """استخراج المعطيات الرياضية من النص الإنجليزي باستخدام AI"""
    prompt = f"""
    You are a math assistant. Extract parameters from this calculus volume problem:
    "{question_text}"
    Return ONLY a JSON object with these keys: 
    "f": (top function), "g": (bottom function, 0 if none), "a": (lower limit), "b": (upper limit), "axis": ("x" or "y").
    Example: {{"f": "sqrt(x)", "g": "0", "a": 0, "b": 4, "axis": "x"}}
    """
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}]
        )
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        st.error(f"Error in AI parsing: {e}")
        return None

# 3. واجهة الإدخال
user_input = st.text_area("أدخل السؤال كاملاً بالإنجليزية:", 
                          placeholder="Example: Find the volume of the solid generated by revolving the region bounded by y = x^2 and y = 4 about the x-axis from x=0 to x=2.")

if st.button("حل المسألة ورسم الخطوات"):
    if not user_input:
        st.warning("يرجى كتابة السؤال أولاً.")
    else:
        with st.spinner("جاري تحليل السؤال رياضياً..."):
            # استخراج البيانات
            data = parse_problem_with_ai(user_input)
            
            if data:
                # تحويل النصوص إلى رموز رياضية
                x = symbols('x')
                f_expr = sympify(data['f'])
                g_expr = sympify(data['g'])
                a = float(data['a'])
                b = float(data['b'])
                
                # تحديد النوع: Disk أم Washer
                method = "Washer Method" if g_expr != 0 else "Disk Method"
                
                st.divider()
                st.header(f"Results: {method}")
                
                # 4. عرض خطوات الحل (Step-by-Step)
                col1, col2 = st.columns([1, 1])
                
                with col1:
                    st.subheader("Solution Steps:")
                    
                    if method == "Disk Method":
                        st.latex(r"V = \pi \int_{a}^{b} [f(x)]^2 dx")
                        integrand = f_expr**2
                    else:
                        st.latex(r"V = \pi \int_{a}^{b} ([R(x)]^2 - [r(x)]^2) dx")
                        integrand = f_expr**2 - g_expr**2
                    
                    st.write(f"**Integral Setup:**")
                    st.latex(f"V = \pi \int_{{{a}}}^{{{b}}} ({integrand}) dx")
                    
                    # حساب التكامل
                    antiderivative = integrate(integrand, x)
                    volume_final = integrate(integrand, (x, a, b)) * pi
                    
                    st.write("**Antiderivative:**")
                    st.latex(f"\pi \left[ {antiderivative} \\right]_{{{a}}}^{{{b}}}")
                    
                    st.success(f"Final Volume ≈ {float(volume_final.evalf()):.4f} cubic units")

                with col2:
                    st.subheader("Visualization:")
                    # رسم بياني للمنطقة
                    x_vals = np.linspace(a, b, 200)
                    f_num = lambdify(x, f_expr, 'numpy')
                    g_num = lambdify(x, g_expr, 'numpy')
                    
                    fig, ax = plt.subplots()
                    ax.plot(x_vals, f_num(x_vals), label='Upper $f(x)$', color='red')
                    ax.plot(x_vals, g_num(x_vals), label='Lower $g(x)$', color='blue')
                    ax.fill_between(x_vals, f_num(x_vals), g_num(x_vals), color='gray', alpha=0.3)
                    ax.axhline(0, color='black', linewidth=1)
                    ax.set_title("Region to be Revolved")
                    ax.legend()
                    st.pyplot(fig)

# 5. ت
